### ISSUE TITLE
How to use phpstorm:// links

### ISSUE THREAD

**Issue by ejunker** [grifart/phpstan-oneline#14]
I was using version 0.2.2 with AwesomeConsole and PHPStorm and it was working well. I upgraded to version 0.3.0 and now I get the phpstorm:// links showing as text, not as clickable links. I tried AwesomeConsole and the native PHPStorm console. How do I get the links to work? I am using PHPStorm 2019.3 on macOS. Am I missing something?

**Comment by ejunker** [comment]
I'm also seeing text like this in the PHPStorm terminal:

```
<error severity="error" message="Found 15 errors" />
```

**Comment by Slamdunk** [comment]
Hi, I've the same issue after upgrading to PHPStorm 2019.3:

![immagine](https://user-images.githubusercontent.com/152236/72705482-db910b00-3b5b-11ea-8724-491cc6e58970.png)

@jkuchar any guess on where the issue could be?

**Comment by Slamdunk** [comment]
I should note the adding this to my `phpstan.neon` and running with `--error-format=compact` solved the issue:
```yaml
parameters:
    compact:
        format: "{absolutePath}:{line} {error}"
```

**Comment by jkuchar** [comment]
It can lay in two things:

- something changed in the output from phpstan (I do not think so)
- PHPStorm changes interpretation of utf-8 characters (please try to search for bug in YouTrack and let me know if you can find something)

**Comment by jkuchar** [comment]
Have anyone discoverred anything?

**Comment by Slamdunk** [comment]
I haven't dug further as the workaround is easy and enough, sorry

**Comment by jkuchar** [comment]
Reverted master back to classic behaviour.

**Comment by jkuchar** [comment]
Released in https://github.com/grifart/phpstan-oneline/releases/tag/v0.3.1
