### ISSUE TITLE
More output formats?

### ISSUE THREAD

**Issue by jkuchar** [grifart/phpstan-oneline#4]
Try to experiment with these output formats:

- [x] two lines
- [x] three lines
- [x] with explicit links #3

**Comment by enumag** [comment]
I'm thinking about ErrorFormatter same as the current one with configurable format:

```
// one line (current version)
'{link} {error}'
// two lines
"{link}\n{error}"
// three lines
"{link}\n{error}\n"
```

It would slightly complicate the installation because you would have tu explicitly use the service in your phpstan.neon

```
services:
	errorFormatter.oneline:
		class: Grifart\PhpstanOneLine\OneLineErrorFormatter
```

and explicitly configure the format argument if you didn't like the default.

Thoughts?

**Comment by jkuchar** [comment]
There can be more then `config.neon`. What about `compact.neon` which will make it configurable using `parameters:`

**Comment by jkuchar** [comment]
Configurable using [phpstan.neon](https://github.com/grifart/phpstan-oneline#custom-error-format)
