### ISSUE TITLE
Compatibility with shim version of PHPStan

### ISSUE THREAD

**Issue by calvera** [grifart/phpstan-oneline#6]
Fatal error: Declaration of Grifart\PhpstanOneLine\CompactErrorFormatter::formatErrors(PHPStan\Command\AnalysisResult $analysisResult, Symfony\Component\Console\Style\OutputStyle $style): int must be compatible with PHPStan\Command\ErrorFormatter\ErrorFormatter::formatErrors(PHPStan\Command\AnalysisResult $analysisResult, _HumbugBox5fa914f81481\Symfony\Component\Console\Style\OutputStyle $style): int in /app/vendor/grifart/phpstan-oneline/src/CompactErrorFormatter.php on line 10

PHP 7.2.13 (cli) (built: Dec 10 2018 14:26:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

        "grifart/phpstan-oneline": "^0.2.0",
        "phpstan/phpstan-doctrine": "^0.10",
        "phpstan/phpstan-shim": "^0.10",
        "phpstan/phpstan-symfony": "^0.10",

**Comment by jkuchar** [comment]
shim version is currently not supported (as any output handler cannot work with shim version).

There is [work in progress on next phpstan version which will solve this](https://github.com/phpstan/phpstan/pull/1685)

**Comment by jkuchar** [comment]
This is going to be fixed with phpstan `0.12`

**Comment by jkuchar** [comment]
fixed in https://github.com/grifart/phpstan-oneline/releases/tag/v0.3.0-beta1

please let me know if it breaks anything
