### ISSUE TITLE
Any idea how to use it via phpstan.phar? 

### ISSUE THREAD

**Issue by voku** [grifart/phpstan-oneline#8]
How to autoload the class, so that I can use it in the config?

**Comment by jkuchar** [comment]
I'm not sure if any extensions can be loaded from `.phar`. Is there any way @OndrejMirtes ?

**Comment by ondrejmirtes** [comment]
I think the autoloading works the same way. You need to have the class in `autoload`/`autoload-dev` in composer.json (when available) or provide your own autoloader file (or manually require all files) in PHPStan's `-a` option.

**Comment by voku** [comment]
Yes and no ... I can use a autoloader for the new class, but then I see a fatal error - that classes from phpstan itself are not available. 

So I added a hack ...

```
// Autoload classes for phpstan phar
if (!class_exists('\\PHPStan\\Rules\\Rule')) {
    if (\PHP_VERSION_ID >= 70100) {
        require_once 'phar://' . DIR_FRAMEWORK . '/thirdparty/phpstan_php7_1.phar/vendor/autoload.php';
    } else {
        require_once 'phar://' . DIR_FRAMEWORK . '/thirdparty/phpstan_php7_0.phar/vendor/autoload.php';
    }
}
```

... but I still get an error from ```ContainerBuilder.php line 456``` that a class from service was not found?

-> maybe I need to install phpstan global and not using the phar file?! -> so I will close this issue
